### ISSUE TITLE
Check preconditions in the form

### ISSUE THREAD

**Issue by onmax** [Albermonte/Nimiq-Multi-Cashlink#15]
Something like this
![image](https://user-images.githubusercontent.com/22072217/116820462-9688c080-ab75-11eb-941f-ea0b3d1edf9d.png)
shouldn't be possible. 

It should check parameter before giving the option to the user to create a new multicashlink???

Or do we check  inputs after user clicked ?

**Comment by Albermonte** [comment]
A message will pop after form submited
![image](https://user-images.githubusercontent.com/14013679/116822724-c5f0fa80-ab80-11eb-9001-ec18e55f68ab.png)

Also only whole numbers are allowed
![image](https://user-images.githubusercontent.com/14013679/116822795-25e7a100-ab81-11eb-8678-4721c58d069a.png)


But checking real time whould be better

**Comment by onmax** [comment]
sorry, i dont speak: "el valor debe de ser superior"
